branch-defaults:
  default:
    environment: crypto-bank-client-dev
    group_suffix: null
global:
  application_name: crypto-bank-client
  branch: null
  default_ec2_keyname: crypto-bank-client
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
