name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn with Corepack
        run: corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install
        working-directory: ./client

      - name: Build
        run: yarn build
        working-directory: ./client

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade awscli

      - name: Install Elastic Beanstalk CLI
        run: pip3 install awsebcli --upgrade

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region your-aws-region

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          EB_ENV_NAME: 'crypto-bank-client-dev'
        run: |
          cd client
          zip -r deploy.zip .
          cd ..
          npx eb deploy $EB_ENV_NAME --region $AWS_REGION --staged
