name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn with Corepack
        run: corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          EB_ENV_NAME: 'crypto-bank-client-dev'
        run: |
          cd client
          zip -r deploy.zip .
          cd ..
          npx eb deploy $EB_ENV_NAME --region $AWS_REGION --staged
